<?php

/**
 * @file
 * Installation functions for Lorem ipsum test module.
 */

use Drupal\user\RoleInterface;

/**
 * Implements hook_install().
 * Visit https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Extension%21module.api.php/function/hook_install/8.2.x
 */
function lorem_ipsum_test_install() {
  user_role_change_permissions(RoleInterface::ANONYMOUS_ID, array(
    'generate lorem ipsum test' => TRUE,
  ));
}
